---
- name: Check ssh existing configuration files
  ansible.builtin.find:
    paths: /etc/ssh/ssh_config.d
    patterns: "*.conf"
  when: ssh_client_cleanup
  register: existing_config

- name: Remove existing configuration files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ existing_config.files }}"
  when: ssh_client_cleanup
  notify: Restart sshd

- name: Check sshd existing configuration files
  ansible.builtin.find:
    paths: /etc/ssh/sshd_config.d
    patterns: "*.conf"
  when: ssh_server_cleanup
  register: existing_config

- name: Remove existing configuration files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ existing_config.files }}"
  when: ssh_server_cleanup
  notify: Restart sshd
